### ISSUE TITLE
Segmentation fault on GEMM node

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#337] opened 2019-11-28 03:38 UTC
This is a simply example:

```
#!/usr/bin/env python

import torch
import numpy as np
from torch import nn
import onnxruntime
from torchvision.ops import RoIAlign
from torchvision.ops import nms
try:
    from alfred.dl.torch.common import device
except ImportError:
    print('install alfred-py first, pip install alfred-py')
from register_onnx_ops import register_custom_op


register_custom_op()


torch.manual_seed(1024)
np.random.seed(1024)

model_p = 'model_nms.onnx'

roi_boxes = np.random.random([100, 4])
score = np.random.random([100])


class TinyModel(nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        self.expander = nn.Conv1d(100, 1, 1, 1)
        self.roi_boxes = roi_boxes
        self.atom = torch.tensor([[0.22], [0.14], [0.1], [0.4]]).to(device)

    def forward(self, x: torch.Tensor):
        score = torch.mm(x, self.atom)
        print(score.shape)
        score = score.squeeze(dim=1)
        print(score.shape)
        x = nms(x, score, 0.6)
        return x


def export_onnx():
    model = TinyModel().to(device)
    sample_input = torch.rand(100, 4).to(device)
    model.eval()
    torch.onnx.export(model, sample_input, model_p, input_names=[
                      'rois'], output_names=['values'], opset_version=10)
    print('onnx model exported. forward now...')
    # forward now

    out_pt = model(sample_input)
    print('pytorch output: {}'.format('-'*80))
    print(out_pt)

if __name__ == "__main__":
    export_onnx()

```

![image](https://user-images.githubusercontent.com/21303438/69775374-824bd180-11d3-11ea-888c-588a742e6b24.png)

When convert this model, it segmentation fault:

```
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
Parsing model
[1]    27162 segmentation fault  onnx2trt model_nms.onnx

```

**Comment by ledinhtri97** [comment] 2020-03-15 16:59
Hello, Could you share module register_custom_op?

**Comment by kevinch-nv** [comment] 2020-12-01 17:27
@jinfagang are you able to repro the segfault on the latest version of onnx-tensorrt?

Also I've noticed that there is a NMS operator in the graph that we currently do not support.

I will be closing this as a duplicate of #267

**Closed** 2020-12-01 17:28 UTC
Labels: duplicate, triaged
