### ISSUE TITLE
No module named 'onnx_tensorrt'

### ISSUE THREAD

**Issue by mx1mx2** [onnx/onnx-tensorrt#447] opened 2020-04-25 03:22 UTC
onnx2trt is ok, but "No module named 'onnx_tensorrt' "in Pycharm

**Comment by Tian14267** [comment] 2020-07-01 01:35
Did you fix it ? I get same error in pycharm. @mx1mx2

**Comment by mk-nvidia** [comment] 2020-10-13 05:12
Closing as dupe of #298 
We're taking a look at this issue.

**Closed by mk-nvidia** 2020-10-13 05:12 UTC
