### ISSUE TITLE
When will NMS and RoiAlign will be supported?

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#289] opened 2019-10-16 09:31 UTC
Does there any walk around for supporting NMS and RoIAlign inside onnx-tensorrt?

the onnx optset 10 had added these 2 ops a long time ago.

**Comment by basaltzhang** [comment] 2020-02-29 13:00
same question

**Comment by ledinhtri97** [comment] 2020-03-15 09:23
+1

**Comment by kevinch-nv** [comment] 2020-11-10 22:02
Closing this as a duplicate of #267

**Closed by kevinch-nv** 2020-11-10 22:02 UTC
Labels: enhancement, triaged
