### ISSUE TITLE
onnx_backend_test.py OnnxBackendRealModelTest "RuntimeError: Failed to build TensorRT engine from network"

### ISSUE THREAD

**Issue by LukeAI** [onnx/onnx-tensorrt#112] opened 2019-02-08 13:51 UTC
The backend tests fail with the cryptic "RuntimeError: Failed to build TensorRT engine from network"

Ubuntu 16.04 Cuda 10, CuDNN 7.4, TensorRT 5.0.2

```
$ python onnx_backend_test.py OnnxBackendRealModelTest
(Unnamed Layer* 0) [Convolution]
(Unnamed Layer* 1) [Activation]
(Unnamed Layer* 2) [LRN]
.
.
.
(Unnamed Layer* 43) [Shuffle]
(Unnamed Layer* 44) [Shuffle]
(Unnamed Layer* 45) [Fully Connected]
(Unnamed Layer* 46) [Softmax]
(1000, 1, 1)
[TensorRT] ERROR: runtime.cpp (24) - Cuda Error in allocate: 2
E
======================================================================
ERROR: test_densenet121_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_inception_v1_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_inception_v2_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_resnet50_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_squeezenet_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_vgg16_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

======================================================================
ERROR: test_vgg19_cuda (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 208, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/luke/.local/lib/python2.7/site-packages/onnx/backend/test/runner/__init__.py", line 229, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 219, in prepare
    return TensorRTBackendRep(model, device, **kwargs)
  File "/home/luke/onnx-tensorrt/onnx_tensorrt/backend.py", line 113, in __init__
    raise RuntimeError("Failed to build TensorRT engine from network")
RuntimeError: Failed to build TensorRT engine from network

----------------------------------------------------------------------
Ran 18 tests in 128.884s

FAILED (errors=7, skipped=9)
```

**Comment by kevinch-nv** [comment] 2020-11-03 21:55
Closing this as duplicate of #110 and #98.

**Closed by kevinch-nv** 2020-11-03 21:55 UTC
Labels: duplicate, triaged, wontfix
