### ISSUE TITLE
Trying to convert .onnx file to .trt and reach to this error: [5] Assertion failed: tensors.count(output.name())

### ISSUE THREAD

**Issue by barzan-hayati** [onnx/onnx-tensorrt#274] opened 2019-09-28 06:30 UTC
I tested standard `yolov3.weights` successfully. At first I converted `yolov3.weights` to `yolov3.onnx` via this repository: [yolov3-tensorrt](https://github.com/xuwanqi/yolov3-tensorrt). Next, I generate `yolov3.trt` via this command: `onnx2trt my_model.onnx -o my_engine.trt`

**Note**: I compiled your repository: **ONNX2TRT** successfully. 

Now I want to convert other `.ONNX` files of `yolov3` or `tiny-yolo` or other type of yolo object detection. But, I recieved this error in output: 
`[5] Assertion failed: tensors.count(output.name())`

All output message:
```
----------------------------------------------------------------
Input filename:   yolov3.onnx
ONNX IR version:  0.0.5
Opset version:    10
Producer name:    NVIDIA TensorRT sample
Producer version: 
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.5) than this parser was built against (0.0.3).
Parsing model
ERROR: /home/aistation/Tools/onnx-tensorrt/ModelImporter.cpp:566 In function importModel:
[5] Assertion failed: tensors.count(output.name())
```

**Comment by tairen99** [comment] 2019-10-25 20:59
Hi, @barzan-hayati,
    I have exact the same issue with my trained tiny yolov2 model.
    Do you find any solution for this issue?
    Thank you!

**Comment by barzan-hayati** [comment] 2019-10-26 06:33
@tairen99 
Since I should finish this project with any method, I use method of converting these weights by `pre installed nano card tools`. If you want to use converted tensorrt weights in `Jetson Nano` or `Xavior` or ..., you could download `deep stream tools` for those devices.

I try to use existing converter in github, but I could not convert `yolo weights` to `tensorrt`. I didn't check convertor in `docker` .
 I hope it be helpful. If you find any method please share it.

**Comment by tairen99** [comment] 2019-10-28 16:20
Hi, @barzan-hayati,
     Thank you for your reply.
      I guess the docker will be the same version of non-docker version.
      Sure, if I can figure out something, I will let you know.

**Comment by kevinch-nv** [comment] 2020-11-10 19:33
This issue should be fixed in later versions of ONNX-TensorRT. Can you try with the latest release branch to see if this is still reproduceable?

**Comment by kevinch-nv** [comment] 2020-12-01 16:37
Closing due to inactivity - if you are still having issues with the latest version of onnx-tensorrt feel free to open a new issue.

**Closed by kevinch-nv** 2020-12-01 16:37 UTC
Labels: repro requested, triaged
