### ISSUE TITLE
torch.max or ArgMax translate to TensorRT ITopK layer is too slow

### ISSUE THREAD

**Issue by jinfagang** [onnx/onnx-tensorrt#671] opened 2021-04-21 08:12 UTC
Please note that max do not need TopK, TopK caused too many latency:

![image](https://user-images.githubusercontent.com/21303438/115520038-521b3c00-a2bc-11eb-9528-0f21fb75c64e.png)

max algorithm could be more efficient then TopK

**Comment by Eashwar93** [comment] 2021-04-23 09:48
@jinfagang I think I have a similar problem when compiling the model for jetson Nano

```
Timing Runner: ArgMax_95 (TopK)
Tactic: 0 time 274.198
Tactic: 1 time 1354.22
Tactic: 3 time 2.5888
../builder/cudnnBuilderUtils.cpp (427) - Cuda Error in findFastestTactic: 702 (the launch timed out and was terminated)
../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 702 (the launch timed out and was terminated)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
Aborted (core dumped)
```
Do you have any solution for the same?

**Comment by jinfagang** [comment] 2021-04-23 15:06
@Eashwar93 How did u get this error? By runing what procedure?

**Comment by Eashwar93** [comment] 2021-04-23 15:14
@jinfagang I am trying to convert a segmentation model from onnx to tensorrt. I am using the code from [this](https://github.com/CoinCheung/BiSeNet/blob/master/tensorrt/trt_dep.cpp) repo.

I also tried another way but I  get the same error when I try to use [this](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/trtexec) repo. I use the command ./trtexec --onnx=model.onnx

**Comment by jinfagang** [comment] 2021-04-25 02:55
@Eashwar93 TensorRT's topk layer definitely have efficiency issue, but I can understand why they do this, it's because of mem usage concern, your temp solution could be make your max operation on smaller tensor WH.

**Comment by Eashwar93** [comment] 2021-04-26 09:37
@jinfagang Could you explain me what the solution is in a bit more detailed way. I am really new to this area of deploying Neural Networks

**Comment by kevinch-nv** [comment] 2021-05-03 17:54
@jinfagang closing is as a duplicate of #669. @Eashwar93 please open a new issue for your problem, it'll be easier to track that way.

**Closed by kevinch-nv** 2021-05-03 17:54 UTC
Labels: duplicate, triaged
