### ISSUE TITLE
While parsing node number 94 [Constant]: ERROR: ModelImporter.cpp:492 In function importModel: [7] Assertion failed: _importer_ctx.tensors().at(output.name()).is_tensor()

### ISSUE THREAD

**Issue by daixiangzi** [onnx/onnx-tensorrt#425] opened 2020-04-04 01:45 UTC

**Comment by kevinch-nv** [comment] 2020-12-17 16:47
@daixiangzi can your reproduce this error with the latest TRT version?

**Comment by kevinch-nv** [comment] 2021-02-01 18:19
Closing due to no repro., if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.

**Closed by kevinch-nv** 2021-02-01 18:19 UTC
Labels: repro requested, triaged
