### ISSUE TITLE
In function parseGraph: [8] No importer registered for op: NonMaxSuppression

### ISSUE THREAD

**Issue by rgc183** [onnx/onnx-tensorrt#444] opened 2020-04-23 17:39 UTC
I wanted to know if anyone has already implemented this op.
 When are we planning to add support for this?

**Comment by rgc183** [comment] 2020-04-24 19:56
I am trying to write Importer for this app and struggling with input params. The issue is already posted here: https://github.com/NVIDIA/TensorRT/issues/510, looking for help here.

**Comment by kevinch-nv** [comment] 2020-12-18 17:38
Closing as duplicate of NVIDIA/TensorRT#510

**Closed by kevinch-nv** 2020-12-18 17:38 UTC
Labels: duplicate, triaged
