### ISSUE TITLE
No module named 'onnx_tensorrt' 

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx-tensorrt#492] opened 2020-07-01 01:40 UTC
I use `import onnx_tensorrt.backend as backend` in code, but get error:
`ModuleNotFoundError:` No module named 'onnx_tensorrt'`

My onnx-tensorrt is ok ,and I can use onnx2trt，but this error, Does somebody knows?

**Comment by kolingv** [comment] 2020-07-02 10:46
I encounterted the same error inside docker, it seems that when comes to "python setup.py build && python setup.py install" failed.

**Comment by mk-nvidia** [comment] 2020-10-13 05:13
Closing as dupe of #298 
We're taking a look at this issue.

**Closed by mk-nvidia** 2020-10-13 05:13 UTC
