### ISSUE TITLE
Pad-11 parsing does not handle non-float32 constant values

### ISSUE THREAD

**Issue by toreolsensan** [onnx/onnx-tensorrt#658] opened 2021-03-22 13:22 UTC
Our Pad layers have float16 constant_weight values, which even when they are actually all 0 sometimes fail to pass the assertion that value == .0f. It seems the Pad importer function assumes the value is always 32-bit, causing not only the 16-bit value but also the following two bytes to be included. So depending on what follows the Pad layer the assertion may fail.

Now, I don't know how to properly handle float16 within onnx-tensorrt so this isn't a proposed fix, but to verify my hypothesis I did the following change to ensure only two bytes are parsed:

```
diff --git a/builtin_op_importers.cpp b/builtin_op_importers.cpp
index fb5ab88..2489c50 100644
--- a/builtin_op_importers.cpp
+++ b/builtin_op_importers.cpp
@@ -2570,7 +2570,16 @@ DEFINE_BUILTIN_OP_IMPORTER(Pad)
             ASSERT(inputs.at(2).is_weights(), ErrorCode::kUNSUPPORTED_NODE);
             auto padWeight = inputs.at(2).weights();
             ASSERT(padWeight.count() == 1, ErrorCode::kINVALID_NODE);
-            value = static_cast<float*>(padWeight.values)[0];
+            switch (padWeight.type) {
+                case ::ONNX_NAMESPACE::TensorProto::FLOAT16: {
+                    uint16_t v{0};
+                    memcpy(&v, padWeight.values, 2);
+                    value = v;
+                    break;
+                }
+                default:
+                    value = static_cast<float*>(padWeight.values)[0];
+            }
         }
     }

```

Obviously this isn't a general solution but it helps us, and I hope perhaps this information would be useful to someone who knows this project better.

**Comment by oxana-nvidia** [comment] 2022-05-26 02:09
Hi @toreolsensan,
Thanks for providing detailed information! 

The issue is fixed in TensorRT 8.4 and the change will be integrated to this repo.  Current TensorRT 8.4 code:
         
```
                 case ::ONNX_NAMESPACE::TensorProto::FLOAT:
                    value = static_cast<float const*>(padWeight.values)[0];
                    isValueSet = true;
                    break;
                case ::ONNX_NAMESPACE::TensorProto::FLOAT16:
                    value = float(reinterpret_cast<half_float::half const*>(padWeight.values)[0]);
                    isValueSet = true;
                    break;
                default:
                    // we use trt constant layer to do the data type convertion
                    break;
```

**Closed as completed** 2022-06-22 17:17 UTC
Labels: triaged
