### ISSUE TITLE
TensorRT doesn't accelerate

### ISSUE THREAD

**Issue by Faldict** [onnx/onnx-tensorrt#35] opened 2018-07-21 11:38 UTC
Compared with original models, the time cost using tensorrt engine is two times more. So why doesn't it accelerate the running speed? The figure below shows the MXNet model and TensorRT engine's running time per batch.

![pk](https://user-images.githubusercontent.com/15966802/43067674-956b9e16-8e9a-11e8-91fc-dde142eab319.png)

Sometimes, it occurs such errors:

```
Cuda error in file src/implicit_gemm.cu at line 1214: invalid resource handle
[TensorRT] ERROR: customWinogradConvActLayer.cpp (308) - Cuda Error in execute: 33
[TensorRT] ERROR: customWinogradConvActLayer.cpp (308) - Cuda Error in execute: 33
```
It's very weird, and I don't know what happened.

**Comment by JesseWong333** [comment] 2018-07-22 13:20
Me too...I also found using tensorrt engine is about 40% lower than running pytorch code directly. That's strange.

**Comment by Faldict** [comment] 2018-07-25 05:31
@yinghai The experiments, running on a PC with Ubuntu 16.04 and a GTX 1060 GPU, test LeNet (trained by myself) and Inception-7 (download from mxnet-model-gallery) models.

At first, I used your `tensorrt_engine`.

```
from tensorrt_engine import Engine

...

engine = Engine(trt_engine)
engine.run(data)
```

Unfortunately, it sometimes occured some Cuda error, as described before. Then I followed the TensorRT official documents:

```
stream = cuda.Stream()
cuda.memcpy_htod_async(d_input, data, stream)
context.enqueue(batch_size, bindings, stream.handle, None)
cuda.memcpy_dtoh_async(output, d_output, stream)
stream.synchronize()
```  

The time cost is measured by `time.time()` manually.

**Comment by benbarsdell** [comment] 2018-07-30 17:36
What max_batch_size are you specifying? TensorRT performance will be best when batch_size = max_batch_size.

**Comment by Faldict** [comment] 2018-08-08 02:17
@benbarsdell Thanks for your reply. I tried with `batch_size = max_batch_size = 32`, but it still performed slower than the original MXNet model. So what can I do?

**Comment by cliffwoolley** [comment] 2018-08-08 05:04
We should probably separate the error message from the performance problem.  I suggest let's get the error condition sorted out first.

> Cuda error in file src/implicit_gemm.cu at line 1214: invalid resource handle
> [TensorRT] ERROR: customWinogradConvActLayer.cpp (308) - Cuda Error in execute: 33

So that's from cuDNN.  Exactly which version of cuDNN is this?  And while we're at it, which CUDA, which TensorRT versions?

**Comment by Faldict** [comment] 2018-08-08 12:11
I used cuDNN 7, CUDA 9.0 and TensorRT 4.0. All of them are downloaded from nvidia official websites and installed following their instructions.

**Comment by cliffwoolley** [comment] 2018-08-08 13:49
With apologies, can you say _exactly_ which cuDNN version?  There have been around ten different released versions numbered like 7.x.y.

**Comment by Faldict** [comment] 2018-08-09 02:09
@cliffwoolley Sorry, I just guess it doesn't matters... I recheck my cuDNN version, typing

```
cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
```

and it gets

```
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

So it seems that the cuDNN version is 7.0.4, right?

**Comment by cliffwoolley** [comment] 2018-08-09 06:04
If you're able to try one of the cuDNN 7.1 or 7.2 builds -- and if that doesn't already fix the problem for you -- then we should be able to use the API logging feature that was added in cuDNN 7.1 to chase down where the problem is happening.

Thanks,
Cliff

**Comment by Faldict** [comment] 2018-08-09 08:59
@cliffwoolley It works fine after I upgraded to cuDNN 7.2.1......at least, until now. But the memory cost to run the `tensorrt_engine` is too large, which becomes another reason for me to use `tensorrt` directly. Here is a simplified version of my code to use the `tensorrt_engine`. Could you plz take a look and point out where I can optimize it?

```
import numpy as np
import tensorrt as trt
from tensorrt_engine import Engine

G_LOGGER = trt.infer.ConsoleLogger(trt.infer.LogSeverity.INFO)
trt_engine = trt.utils.load_engine(G_LOGGER, 'model/Inception-7.trt')
engine = Engine(trt_engine)
batch_size = 16

data = np.random.normal(0, 1, size=(batch_size, 3, 299, 299)).astype('float32')
output = engine.run([data])
```

Many thanks!

**Comment by cliffwoolley** [comment] 2018-08-10 00:10
@benbarsdell Any further advice you can offer here?

**Comment by cliffwoolley** [comment] 2018-08-10 18:15
@Faldict -- It's a bit of an aside, but https://github.com/apache/incubator-mxnet/pull/11325 was merged to the MXNet master branch today.  It uses onnx-tensorrt on your behalf under the hood.  I wonder if you have a better experience using that higher-level interface?

**Comment by Faldict** [comment] 2018-08-11 14:43
@cliffwoolley I have followed that PR from last month. Now that it is merged, I'll try it.

**Comment by liuchang8am** [comment] 2019-05-18 04:15
any updates? Same issue here, tensorrt does not accelerate onnx(converted from pytorch) models

**Comment by kobewangSky** [comment] 2019-11-20 07:33
try to save .trt and load a again

**Comment by kevinch-nv** [comment] 2020-10-25 08:46
Does anyone have a repro for this issue with the latest version of TensorRT (7.2)?

**Comment by kevinch-nv** [comment] 2020-12-01 16:21
Closing due to inactivity - if you are still having issues with the latest version of onnx-tensorrt feel free to open a new issue.

**Closed by kevinch-nv** 2020-12-01 16:21 UTC
Labels: repro requested, triaged

**Comment by ttanzhiqiang** [comment] 2021-06-30 03:31
https://github.com/ttanzhiqiang/onnx_tensorrt_project
