### ISSUE TITLE
Assertion failed: ctx->tensors().count(inputName) 

### ISSUE THREAD

**Issue by ganliqiang** [onnx/onnx-tensorrt#428] opened 2020-04-07 07:36 UTC
when i run the example  this error occus;
i user pytorch==1..4.0 onnx=1.6.0 tensorrt = 7.0.0 and opset =11 
i donnot know why this error occus  ,someone says opset11 is the key error but when i use opset10 annother error occur:  Assertion failed: scales.is_weights() && "Resize scales must be an initializer!"
is the bilinear mode is supported in this version .how should i solve this problem thanks in advances.

**Comment by DJMeng** [comment] 2020-05-29 03:01
Have you solved it? Thanks

**Comment by zldrobit** [comment] 2020-10-20 03:11
@ganliqiang Maybe you could try using tensorrt 7.1 for better onnx opset 10/11 supports.
However, I believe the cause is in onnx-tensorrt.

**Comment by kevinch-nv** [comment] 2020-12-18 17:27
This should be fixed in later releases of TensorRT with opset 11 resize. Can you try upgrading to the latest release?

**Comment by kevinch-nv** [comment] 2021-02-01 18:19
Closing due to no activity in this thread, if you are still having troubles feel free to open a new issue with a repro on the latest version of TRT.

**Closed by kevinch-nv** 2021-02-01 18:19 UTC
Labels: repro requested, triaged
