### ISSUE TITLE
two inputs (data and weights) are allowed only in explicit-quantization mode.

### ISSUE THREAD

**Issue by lsdNorman** [onnx/onnx-tensorrt#790] opened 2021-12-20 08:59 UTC
root@90e0df0b7943:/home/TensorRT/parsers/onnx/build# ./onnx2trt /home/my.onnx -o my.trt
----------------------------------------------------------------
Input filename:   /home/my.onnx
ONNX IR version:  0.0.6
Opset version:    12
Producer name:    pytorch
Producer version: 1.8
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
Parsing model
[2021-12-20 08:58:04 WARNING] onnx2trt_utils.cpp:367: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2021-12-20 08:58:04   ERROR] Conv_90: two inputs (data and weights) are allowed only in explicit-quantization mode.
While parsing node number 90 [Conv -> "883"]:
ERROR: ModelImporter.cpp:177 In function parseGraph:
[6] Invalid Node - Conv_90
Conv_90: two inputs (data and weights) are allowed only in explicit-quantization mode.

**Comment by SsTtOoNnEe** [comment] 2022-01-03 02:29
I have met the same issue. Any solutions?

**Comment by liguang-ops** [comment] 2022-03-21 11:28
I have met the same issue too. Any advice is greatly appreciated！

**Comment by kevinch-nv** [comment] 2022-03-21 18:45
This is a known limitation of TensorRT - `weights` input to conv must be a constant outside of explicit quantization mode (i.e. for QDQ models).  Closing this as duplicate of https://github.com/onnx/onnx-tensorrt/issues/609

**Closed** 2022-03-21 18:46 UTC
Labels: duplicate, triaged
