### ISSUE TITLE
No importer registered for op: NonZero

### ISSUE THREAD

**Issue by Raneee** [onnx/onnx-tensorrt#458] opened 2020-05-12 08:13 UTC
any one get solution of this problem? or other op to replace nonzero?  thx!

**Comment by rgc183** [comment] 2020-05-14 21:23
same problem.

**Comment by manhongnie** [comment] 2020-06-21 14:22
> same problem.

Have you solved？

**Comment by kevinch-nv** [comment] 2020-12-28 18:46
Currently we do not have support for NonZero, marking this as a duplicate of #401

**Closed** 2020-12-28 18:47 UTC
Labels: duplicate, triaged
