### ISSUE TITLE
How to deserialize a network with custom plug-ins? Creatorfactory is available for versions below 7.0, how to do it for versions above 7.0?

### ISSUE THREAD

**Issue by scuizhibin** [onnx/onnx-tensorrt#652] opened 2021-03-08 23:43 UTC

**Comment by zzypeak** [comment] 2021-03-19 09:42
I've got the same problem, it works well in cpp code blow,
```
mPlugins = nvonnxparser::createPluginFactory(gLogger);
std::cout << "deserializing" << std::endl;
mRunTime = nvinfer1::createInferRuntime(gLogger);
assert(mRunTime != nullptr);
mEngine= mRunTime->deserializeCudaEngine(data.get(), length, mPlugins);
assert(mEngine != nullptr);
```
but i don't know how to do this in python.

**Comment by sainttelant** [comment] 2022-03-08 08:53
@scuizhibin yes, any solutions??? currently, i use tensorrt8.2GA

**Comment by kevinch-nv** [comment] 2022-04-01 00:14
Closing as duplicate of https://github.com/onnx/onnx-tensorrt/issues/815

**Closed by kevinch-nv** 2022-04-01 00:14 UTC
