### ISSUE TITLE
python onnx_backend_test.py doesn't do much?

### ISSUE THREAD

**Issue by LukeAI** [onnx/onnx-tensorrt#110] opened 2019-02-04 12:22 UTC
```
test_abs_cpu (__main__.OnnxBackendNodeTest) ... skipped u"Backend doesn't support device CPU"
test_abs_cuda (__main__.OnnxBackendNodeTest) ... (Unnamed Layer* 0) [Unary]
(4, 5)
> /home/luke/onnx-tensorrt/onnx_tensorrt/backend.py(111)__init__()
-> trt_engine = self.builder.build_cuda_engine(self.network)
(Pdb)
```
Then it just stops, no cpu activity - does this mean success or failure or something else?
Python 2.7, Ubuntu 16.04, Tensorrt 5, i7-8750H

**Comment by yjn870** [comment] 2019-02-08 13:08
You might remove below the line then it will be fine.

https://github.com/onnx/onnx-tensorrt/blob/master/onnx_tensorrt/backend.py#L109

**Comment by LukeAI** [comment] 2019-02-08 13:24
Thanks for reply, it now segfaults as follows:
```
 $ python onnx_backend_test.py -v
test_abs_cpu (__main__.OnnxBackendNodeTest) ... skipped u"Backend doesn't support device CPU"
test_abs_cuda (__main__.OnnxBackendNodeTest) ... (Unnamed Layer* 0) [Unary]
(4, 5)
ok
test_add_bcast_cpu (__main__.OnnxBackendNodeTest) ... skipped u"Backend doesn't support device CPU"
test_add_bcast_cuda (__main__.OnnxBackendNodeTest) ... (Unnamed Layer* 0) [Constant]
(Unnamed Layer* 1) [ElementWise]
(4, 5)
ok
test_add_cpu (__main__.OnnxBackendNodeTest) ... skipped u"Backend doesn't support device CPU"
test_add_cuda (__main__.OnnxBackendNodeTest) ... Segmentation fault (core dumped)

$ python3 onnx_backend_test.py -v
test_abs_cpu (__main__.OnnxBackendNodeModelTest) ... skipped "Backend doesn't support device CPU"
test_abs_cuda (__main__.OnnxBackendNodeModelTest) ... (Unnamed Layer* 0) [Unary]
(4, 5)
ok
test_acos_cpu (__main__.OnnxBackendNodeModelTest) ... skipped 'matched exclude pattern "[a-z,_]*_acos_[a-z,_]*"'
test_acos_cuda (__main__.OnnxBackendNodeModelTest) ... skipped 'matched exclude pattern "[a-z,_]*_acos_[a-z,_]*"'
test_acos_example_cpu (__main__.OnnxBackendNodeModelTest) ... skipped 'matched exclude pattern "[a-z,_]*_acos_[a-z,_]*"'
test_acos_example_cuda (__main__.OnnxBackendNodeModelTest) ... skipped 'matched exclude pattern "[a-z,_]*_acos_[a-z,_]*"'
test_add_bcast_cpu (__main__.OnnxBackendNodeModelTest) ... skipped "Backend doesn't support device CPU"
test_add_bcast_cuda (__main__.OnnxBackendNodeModelTest) ... Segmentation fault (core dumped)
```

**Comment by kevinch-nv** [comment] 2020-11-03 21:50
Closing as a duplicate of #98, see my comment in that issue.

**Closed by kevinch-nv** 2020-11-03 21:50 UTC
