### ISSUE TITLE
getPluginCreator could not find plugin NonMaxSuppression version 1

### ISSUE THREAD

**Issue by bnascimento** [onnx/onnx-tensorrt#552] opened 2020-10-27 11:45 UTC
Hi guys, I picked up a tensorflow model .pb (object detection), turned into .onnx with

`python3 -m tf2onnx.convert --saved-model /tmp/export/saved_model/ --output /tmp/export/saved_model/model.onnx --opset 11`

applied the following graph surgeon patch on .onnx file to cast the input tensor to 32f as seen here: https://forums.developer.nvidia.com/t/exporting-tensorflow-models-to-jetson-nano/154185/15 

```
import onnx_graphsurgeon as gs
import onnx
import numpy as np
graph = gs.import_onnx(onnx.load('model.onnx'))
for inp in graph.inputs:
        inp.dtype = np.float32
        onnx.save(gs.export_onnx(graph), 'updated_model.onnx')
```

However when I try to turn it into a tensorRT file with

`onnx2trt /tmp/export/saved_model/updated_model.onnx -o /tmp/export/saved_model/model.trt`

I got:

```
[2020-10-27 11:19:46 WARNING] /opt/onnx-tensorrt/onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[2020-10-27 11:19:46 WARNING] /opt/onnx-tensorrt/onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[2020-10-27 11:19:46 ERROR] INVALID_ARGUMENT: getPluginCreator could not find plugin NonMaxSuppression version 1
While parsing node number 371 [NonMaxSuppression -> “NonMaxSuppression__995:0”]:
ERROR: /opt/onnx-tensorrt/builtin_op_importers.cpp:3777 In function importFallbackPluginImporter:
[8] Assertion failed: creator && “Plugin not found, are the plugin name, version, and namespace correct?”
```

Any ideas how to get past this?
Thanks

**Comment by qraleq** [comment] 2020-11-04 07:54
Same issue here, did you manage to figure out what is the problem?

**Comment by bnascimento** [comment] 2020-11-04 08:32
Not yet, but one of the moderators on the nvidia forums has some ideas. See https://forums.developer.nvidia.com/t/exporting-tensorflow-models-to-jetson-nano/154185/18

**Comment by mosdav** [comment] 2020-11-12 14:34
Same issue - using onnx 1.5.2 cuda 10.2 under Jetson nano

**Comment by DJT777** [comment] 2021-01-07 20:24
Anyone solve this yet?

**Comment by kevinch-nv** [comment] 2021-01-08 22:22
`getPluginCreator could not find plugin` is through the fallback path of the ONNX-TensorRT importer. What this means is that the default library doesn't support the NonMaxSuppression op.

We have plans for adding support for this op in future releases.

**Comment by kevinch-nv** [comment] 2021-01-08 22:24
Marking this as a duplicate of #267

**Closed by kevinch-nv** 2021-01-08 22:24 UTC
Labels: enhancement, triaged

**Comment by DJT777** [comment] 2021-01-09 12:49
@kevinch-nv thank you

**Comment by vilmara** [comment] 2021-01-28 22:29
@DJT777 take a look at `https://github.com/NVIDIA/TensorRT/issues/795` and [](https://github.com/NVIDIA/TensorRT/issues/523)

**Comment by Niloofar-bgh** [comment] 2021-05-14 20:45
@kevinch-nv  Any update on the integration of NonMaxSuppression ?! 
I am trying to convert an SSD model from TF2 model zoo to ONNX and then try to run in on Jetson! I cannot use UFF with TF2 (no Frozen graph in TF2), and ONNX-TensorRT does not support the NonMaxSuppression of the SSD model; any help would be appreciated!

**Comment by tft-robert** [comment] 2021-06-16 07:33
@kevinch-nv Any updates on this issue?

**Comment by Echambouleyron** [comment] 2021-06-28 13:24
Any updates?

**Comment by tft-robert** [comment] 2021-07-05 09:16
@Niloofar-bgh @Echambouleyron  Seems that TensorRT 8.0.1 will have support for NonMaxSuppresion: https://github.com/NVIDIA/TensorRT/blob/master/CHANGELOG.md

`Added EfficientNMS_TRT, EfficientNMS_ONNX_TRT plugins and experimental support for ONNX NonMaxSuppression operator.`

**Comment by Echambouleyron** [comment] 2021-07-05 19:14
@tft-robert thanks a lot. I´ll try that

**Comment by Source82** [comment] 2021-07-22 17:38
> @tft-robert thanks a lot. I´ll try that

Hi did it work for you? any updates

**Comment by Source82** [comment] 2021-07-22 17:39
@Echambouleyron any update? did it work after installing tensorrt v8

**Comment by Echambouleyron** [comment] 2021-07-23 15:26
> @Echambouleyron any update? did it work after installing tensorrt v8

Hello! I have not tried yet because the purpose for converting the model was to deploy it in a Jetson Nano which, I recently realized supports up to version 7.1.3 of Tensor RT. Even though I manage to successfully convert the model, it won´t work in the jetson, right?

**Comment by tft-robert** [comment] 2021-07-25 07:54
@Echambouleyron @Source82 For me it worked perfectly. Managed to convert a tensorflow model from .pb to .onnx, then just copied the onnx model over to the Jetson device. Then I converted it to .trt.

**Comment by Source82** [comment] 2021-07-27 19:30
> @Echambouleyron @Source82 For me it worked perfectly. Managed to convert a tensorflow model from .pb to .onnx, then just copied the onnx model over to the Jetson device. Then I converted it to .trt.

Thanks
