### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by sebawsky** [onnx/onnx-tensorrt#765] opened 2021-10-21 22:42 UTC
## Description

SO: Ubuntu 18.04

I've been trying to install from source onnx-tensorrt in docker by following these steps:

1. Clone repositorio https://github.com/NVIDIA/TensorRT
2. Generate container: ./docker/build.sh --file docker/ubuntu-18.04.Dockerfile --tag tensorrt-ubuntu18.04-cuda11.4 && ./docker/launch.sh --tag tensorrt-ubuntu18.04-cuda11.4 --gpus all
3. Then i install protobuf  >= 3.0.x
4. Clone repo https://github.com/onnx/onnx-tensorrt.git
5. And I follow the installation commands

`$ cd onnx-tensorrt
$ git submodule update --init --recursive
$ mkdir build && cd build
$ cmake .. -DTENSORRT_ROOT=../../TensorRT && make -j`

I have tried the following versions:

- TensorRT  v8.0.1.6 and onnx-tensorrt 8.0-GA
- TensorRT  v8.0.1.6 and onnx-tensorrt 8.0-EA
- TensorRT main (v8.2.0.6) and onnx-tensorrt master
- TensorRT  21.05 and onnx-tensorrt 7.2.1 (Here if I was able to install onnx-tensorrt but I can't convert my yolov3 model (I guess compatibility problems)

The error I get for the first case is the following:

![image](https://user-images.githubusercontent.com/50386332/138366707-6f517cca-88d4-4911-a4a9-9cc92793c7c8.png)

`root@038b8ce97d93:/workspace/onnx-tensorrt/build# make -j8
[  2%] Built target gen_onnx_proto
[ 14%] Built target onnx_proto
[ 15%] Building CXX object CMakeFiles/nvonnxparser.dir/RNNHelpers.cpp.o
[ 16%] Building CXX object CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o
[ 18%] Building CXX object CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o
[ 18%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapedWeights.cpp.o
[ 21%] Building CXX object CMakeFiles/nvonnxparser.dir/OnnxAttrs.cpp.o
[ 21%] Building CXX object CMakeFiles/nvonnxparser_static.dir/onnxErrorRecorder.cpp.o
[ 22%] Building CXX object CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o
[ 76%] Built target onnx
[ 77%] Building CXX object CMakeFiles/nvonnxparser_static.dir/ShapeTensor.cpp.o
/workspace/onnx-tensorrt/builtin_op_importers.cpp: In function 'onnx2trt::NodeImportResult onnx2trt::{anonymous}::QuantDequantLinearHelper(onnx2trt::IImporterContext*, const onnx2trt_onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&, bool)':
/workspace/onnx-tensorrt/builtin_op_importers.cpp:1182:16: error: 'nbDims' was not declared in this scope
         axis = nbDims <= 1 ? 0 : 1;
                ^~~~~~
/workspace/onnx-tensorrt/builtin_op_importers.cpp: In function 'onnx2trt::NodeImportResult onnx2trt::{anonymous}::QuantDequantLinearHelper(onnx2trt::IImporterContext*, const onnx2trt_onnx::NodeProto&, std::vector<onnx2trt::TensorOrWeights>&, bool)':
/workspace/onnx-tensorrt/builtin_op_importers.cpp:1182:16: error: 'nbDims' was not declared in this scope
         axis = nbDims <= 1 ? 0 : 1;
                ^~~~~~
[ 78%] Building CXX object CMakeFiles/nvonnxparser_static.dir/LoopHelpers.cpp.o
[ 80%] Building CXX object CMakeFiles/nvonnxparser_static.dir/RNNHelpers.cpp.o
[ 81%] Building CXX object CMakeFiles/nvonnxparser_static.dir/OnnxAttrs.cpp.o
CMakeFiles/nvonnxparser_static.dir/build.make:88: recipe for target 'CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser_static.dir/builtin_op_importers.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/nvonnxparser.dir/build.make:88: recipe for target 'CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o' failed
make[2]: *** [CMakeFiles/nvonnxparser.dir/builtin_op_importers.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/nvonnxparser.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nvonnxparser_static.dir/all' failed
make[1]: *** [CMakeFiles/nvonnxparser_static.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

Thanks for the help!

**Comment by kevinch-nv** [comment] 2021-11-05 19:49
Will be addressed in https://github.com/onnx/onnx-tensorrt/pull/770

**Comment by sainisanjay** [comment] 2021-11-17 06:43
@kevinch-nv I am getting compilation error 
```
/home/jetsonhack/onnx-tensorrt/onnx2trt_utils.cpp:6:10: fatal error: NvInferSafeRuntime.h: No such file or directory
 #include "NvInferSafeRuntime.h"
```
Command to reproduce: 
cmake .. -DTENSORRT_ROOT=/usr/src/tensorrt/ && make -j

OS: Jetson TX2 (with Jetpack 4.6)
TensorRT: 8.1
Cuda 10.2

In my case there is no include directory inside `/usr/src/tensorrt/
`

**Comment by kevinch-nv** [comment] 2022-02-28 19:04
Closing this issue as the original problem is fixed. @sainisanjay please open another issue if you are having troubles building, from a glance it looks like a version mismatch. You may need to update your Jetpack version to get the latest TRT.

**Closed by kevinch-nv** 2022-02-28 19:04 UTC
Labels: bug, triaged
